import Head from 'next/head'
import Link from '../src/components/Link'
// import styles from '../styles/Home.module.css'

export default function HomePage() {
  return (
    <div className={styles.container}>
      <Head>
        <title>FAQ | Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1>Alura Cases - Página de perguntas</h1>
        <Link href="/">
            Ir para a Home
        </Link>
      </div>
    </div>
  )
}