import HomeScreen from '../src/screens/HomeScreen'

export default HomeScreen

// import Head from 'next/head'
// import React from 'react'
// import Link from '../src/components/Link'
// import styles from '../styles/Home.module.css'

// import Footer from '../src/components/patterns/Footer'

// function Title ({ children, as }) {
//   const Tag = as;

//   return (
//       <React.Fragment>
//           <Tag>
//               {children}
//           </Tag>
//           <style jsx>{`
//               ${Tag} {
//                   color: red;
//                   font-family: sans-serif;
//               }
//           `}</style>
//       </React.Fragment>
//   )
// }

// export default function HomePage() {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Home | Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <div>
//         <Title as="h1">Alura Cases - Hello Word</Title>
//         <Link href="/faq">
//           Ir para o FAQ
//         </Link>
//         <Footer />
//       </div>
//     </div>
//   )
// }